return function ()
	local xor = require(script.Parent.xor)

	describe("arguments", function()
		it("should handle boolean arguments", function()
			expect(function()
				xor(true, false)
			end).never.to.throw()
		end)
		it("should handle non-boolean arguments", function()
			expect(function()
				xor(true, "false")
			end).to.throw()
		end)
		it("should handle missing arguments", function()
			expect(function()
				xor(true)
			end).to.throw()
		end)
	end)
	describe("generics", function()
		it("should handle 0, 0", function()
			local result = xor(false, false)
			expect(result == false).to.equal(true)
		end)
		it("should handle 1, 0", function()
			local result = xor(true, false)
			expect(result == true).to.equal(true)
		end)
		it("should handle 0, 1", function()
			local result = xor(false, true)
			expect(result == true).to.equal(true)
		end)
		it("should handle 1, 1", function()
			local result = xor(true, true)
			expect(result == false).to.equal(true)
		end)
	end)
end
