# why tf doesn't aftman support CI?? i literally hve to use foreman for this bs...

[tools]
selene = { source = "Kampfkarren/selene", version = "0.21.1" }
run-in-roblox = { source = "reimakesgames/run-in-roblox", version = "0.3.3" }
rojo = { source = "rojo-rbx/rojo", version = "7.2.1" }
wally = { source = "UpliftGames/wally", version = "0.3.1" }
