name: Unit

on:
  push:

env:
  ROBLOSECURITY: '_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_8663274E344E480BEDA00230F31AFAB8832691150243995A41EA2A686F5E1C8187E50850C50766554513F484CB9AA85E9B5EC28A20ED8D96ABB878377A837DAD469529F4C26ADBBD2511E20C84107BD179D83A5EF2F497DA9998B7EB25262A39F6FC2CBD24D02A714D5D58F1DB5B4D83D3D1802D350FD5B3DC0D24D4387DD071AE1FEB190355DBAC6C401FAA5920B4704124D15D433560471448A08FFBEA94FF6DB9CA6FEAE799BACA8DCC7367C3ED5DA5DED008B1BDCDBC401B5F7B3B015705847BBF8AF4EC3C555507924ADE268D389C63A924342D63F6E79FB6679AAF50C9552D8DE485E01D151504CC095776C7EE0B5FC046D882E7EDE9B4F7697CC57A1A1EB8CE08B2BAF986C51CD170A1C4045B749C5DE8944AE8315275959F96A4B314D585EE76A1A926FCD256F0C7B321507874F4FD83944C106F4D6FD92BCDEB9B3AE1869B4ACC0B480A4FAE155CE4D62387D828034C695ED6A75002018CBD0D5B8611F91E6D9C095D5ACAA0023D117DFDD0C2EAC92BF9F60A6D45722E71F49738FED453274D'
  RBXIDCHECK: '3277fdb4-5455-4040-9c37-dc11b1f3e388'

jobs:
  testing:
    name: Testing
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Roblox Studio
        uses: OrbitalOwen/roblox-win-installer-action@1.1
        with:
          cookie: ${{ env.ROBLOSECURITY }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Packages
        run: wally install

      - name: Build
        run: rojo build --output test.rbxmx

      - name: Add RBXID to the Windows registry
        run: REG ADD HKCU\Software\RobloxStudioBrowser\roblox.com /t REG_SZ /v .RBXID /d "${{ env.RBXIDCHECK }}"

      # Flip flag that causes issue
      - name: Create fflag overrides
        run: |
          $flags = @{DFIntStudioUseNewLoginDataEndpointHundredthPercent=0; FFlagStudioUseNewLoginDataEndpoint=$false}
          New-Item -Path 'C:/Program Files (x86)/Roblox/Versions/version-*/' -Name "ClientSettings" -ItemType "directory"
          New-Item -Path 'C:/Program Files (x86)/Roblox/Versions/version-*/ClientSettings' -Name "ClientAppSettings.json"
          $flags | ConvertTo-Json -depth 32| set-content -Path 'C:/Program Files (x86)/Roblox/Versions/version-*/ClientSettings/ClientAppSettings.json'

      - name: Run
        run: run-in-roblox --place test.rbxmx --script test.lua
