name: Unit

on:
  push:

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Packages
        run: wally install

      - name: Build
        run: rojo build --output test.rbxmx

      - name: Run
        run: run-in-roblox --place test.rbxmx --script test.lua
