name: Lint

on:
  pull_request:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: rojo build --output test.rbxmx

      - name: Run
        run: run-in-roblox --place test.rbxmx --script test.lua
